server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: born-to-bread-backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # 배포 시 validate로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG # 배포 시 변경
    org.hibernate.type: WARN
    org.crumb.be: INFO

kakao:
  base-url: https://dapi.kakao.com
  client_id: ${KAKAO_CLIENT_ID}
  client_secret: ${KAKAO_CLIENT_SECRET}
  redirect_uri: ${KAKAO_REDIRECT_URI}
  rest-api-key: ${KAKAO_REST_API_KEY}

app:
  google:
    api-key: ${GOOGLE_PLACES_API_KEY}

fastapi:
  base-url: http://${FASTAPI_HOST}:8000

recommend:
  radius: 5000
  limit: 10

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    display-operation-id: true
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    try-it-out-enabled: true
    filter: true
    with-credentials: true
