server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: born-to-bread-backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # 배포 시 validate로 변경
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG # 배포 시 변경
    org.hibernate.type: WARN
    org.crumb.be: INFO

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  client_secret: ${KAKAO_CLIENT_SECRET}
  redirect_uri: ${KAKAO_REDIRECT_URI}

#springdoc:
#  swagger-ui:
#    path: /swagger-ui/index.html
#    display-operation-id: true
#    tags-sorter: alpha
#    operations-sorter: method
#    doc-expansion: none
#    try-it-out-enabled: true
#    filter: true
#    with-credentials: true
